// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IHello is an autogenerated mock type for the IHello type
type IHello struct {
	mock.Mock
}

// Hello provides a mock function with given fields:
func (_m *IHello) Hello() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewIHello interface {
	mock.TestingT
	Cleanup(func())
}

// NewIHello creates a new instance of IHello. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIHello(t mockConstructorTestingTNewIHello) *IHello {
	mock := &IHello{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
