// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewHelloTraceParams creates a new HelloTraceParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewHelloTraceParams() *HelloTraceParams {
	return &HelloTraceParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewHelloTraceParamsWithTimeout creates a new HelloTraceParams object
// with the ability to set a timeout on a request.
func NewHelloTraceParamsWithTimeout(timeout time.Duration) *HelloTraceParams {
	return &HelloTraceParams{
		timeout: timeout,
	}
}

// NewHelloTraceParamsWithContext creates a new HelloTraceParams object
// with the ability to set a context for a request.
func NewHelloTraceParamsWithContext(ctx context.Context) *HelloTraceParams {
	return &HelloTraceParams{
		Context: ctx,
	}
}

// NewHelloTraceParamsWithHTTPClient creates a new HelloTraceParams object
// with the ability to set a custom HTTPClient for a request.
func NewHelloTraceParamsWithHTTPClient(client *http.Client) *HelloTraceParams {
	return &HelloTraceParams{
		HTTPClient: client,
	}
}

/*
HelloTraceParams contains all the parameters to send to the API endpoint

	for the hello trace operation.

	Typically these are written to a http.Request.
*/
type HelloTraceParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the hello trace params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *HelloTraceParams) WithDefaults() *HelloTraceParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the hello trace params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *HelloTraceParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the hello trace params
func (o *HelloTraceParams) WithTimeout(timeout time.Duration) *HelloTraceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the hello trace params
func (o *HelloTraceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the hello trace params
func (o *HelloTraceParams) WithContext(ctx context.Context) *HelloTraceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the hello trace params
func (o *HelloTraceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the hello trace params
func (o *HelloTraceParams) WithHTTPClient(client *http.Client) *HelloTraceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the hello trace params
func (o *HelloTraceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *HelloTraceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
